<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>bkscr</string>
	</array>
    <key>scopeName</key>
    <string>source.bkscr</string>
	<key>name</key>
	<string>BKEngine Scripts</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#label</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#texttag</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#bagelscript</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#bagelscript2</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#linecommand</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#atcommand</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>		
        <key>bkscrlinecomment</key>
        <dict>
            <key>name</key>
            <string>comment.line.bkscr</string>
            <key>match</key>
            <string>//.*$</string>
        </dict>
		
        <key>bkscrlinecomment2</key>
        <dict>
            <key>name</key>
            <string>comment.line.bkscr</string>
            <key>match</key>
            <string>^;.*$</string>
        </dict>
        
        <key>bkscrblockcomment</key>
        <dict>
            <key>name</key>
            <string>comment.block.bkscr</string>
            <key>begin</key>
            <string>/\*</string>
            <key>end</key>
            <string>\*/</string>
        </dict>

		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#bkscrlinecomment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bkscrlinecomment2</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bkscrblockcomment</string>
				</dict>
			</array>
		</dict>
		
		<key>label</key>
		<dict>
			<key>begin</key>
			<string>^\t*(\*[A-Za-z_][A-Za-z0-9_]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.bkscr</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bkscr</string>
						</dict>
					</dict>
				</dict>				
			</array>
		</dict>
		
		<key>texttag</key>
		<dict>
			<key>match</key>
			<string>^\t*【.*?】</string>
			<key>name</key>
			<string>entity.name.tag.bkscr</string>
		</dict>
		
		<key>bagelscript</key>
		<dict>
			<key>begin</key>
			<string>^\t*##\s*$</string>
			<key>end</key>
			<string>^\t*##\s*$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.bagel</string>
				</dict>
			<array>
		</dict>
				
		<key>bagelscript2</key>
		<dict>
			<key>begin</key>
			<string>^\t*#</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.bagel</string>
				</dict>
			<array>
		</dict>

		<key>atcommand</key>
		<dict>
			<key>begin</key>
			<string>^\t*@([A-Za-z_]|[^\x00-\x80])([A-Za-z0-9_]|[^\x00-\x80])*(?=\s|$)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.bkscr</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=\s)((?:[A-Za-z_]|[^\x00-\x80])(?:[A-Za-z0-9_]|[^\x00-\x80])*)=</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.bkscr</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>source.bagel</string>
				</dict>
			</array>
		</dict>
		
		<key>linecommand</key>
		<dict>
			<key>begin</key>
			<string>\[([A-Za-z_]|[^\x00-\x80])([A-Za-z0-9_]|[^\x00-\x80])*(?=\s|\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.bkscr</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.bkscr</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=\s)((?:[A-Za-z_]|[^\x00-\x80])(?:[A-Za-z0-9_]|[^\x00-\x80])*)=</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.bkscr</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>source.bagel</string>
				</dict>
			</array>
		</dict>

	</dict>
	<key>uuid</key>
	<string>6BC8DE6F-2333-4C7E-AC3C-971385945346</string>
</dict>
</plist>
