<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>bkscr</string>
	</array>
    <key>scopeName</key>
    <string>source.bkscr</string>
	<key>name</key>
	<string>BKEngine Scripts</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>bkscr.label</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(^\s*(\*[^\s]+))</string>
			<key>name</key>
			<string>keyword.label</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>bkscr.comment</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(^\s*;.*)</string>
			<key>name</key>
			<string>keyword.SemicommaComment</string>
		</dict>        
 		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>bkscr.comment</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(//.*)</string>
			<key>name</key>
			<string>keyword.LineComment</string>
		</dict>
 		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>bkscr.comment</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(/\*.*?\*/)</string>
			<key>name</key>
			<string>keyword.BlockComment</string>
		</dict>
        
                      
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.catcode.tex</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.keyword.tex</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.tex</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.category.tex</string>
				</dict>
			</dict>
			<key>match</key>
			<string>((\\)catcode)`(?:\\)?.(=)(\d+)</string>
			<key>name</key>
			<string>meta.catcode.tex</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(?=%)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.tex</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>%:</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.tex</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.line.percentage.semicolon.texshop.tex</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(%!TEX) (\S*) =</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.tex</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.line.percentage.directive.texshop.tex</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>%</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.tex</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.line.percentage.tex</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.group.begin.tex</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.group.end.tex</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.group.braces.tex</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>[\[\]]</string>
			<key>name</key>
			<string>punctuation.definition.brackets.tex</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\$\$</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.tex</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\$\$</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.tex</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.other.math.block.tex</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#math</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\\\\</string>
			<key>name</key>
			<string>constant.character.newline.tex</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\$</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.tex</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\$</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.tex</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.other.math.tex</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\\$</string>
					<key>name</key>
					<string>constant.character.escape.tex</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#math</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.tex</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\\)[A-Za-z@]+</string>
			<key>name</key>
			<string>support.function.general.tex</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.keyword.tex</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\\)[^a-zA-Z@]</string>
			<key>name</key>
			<string>constant.character.escape.tex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>«press a-z and space for greek letter»[a-zA-Z]*</string>
			<key>name</key>
			<string>meta.placeholder.greek.tex</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>parser</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>bkscr.parser.keywords</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(enum|if|for|while|do|foreach|function|class|propget|propset|continue|break|return|var|delete|try|throw|this|super|global|int|string|number|const|typeof|instanceof|extends|in|else|then|catch|with|static|switch|case|true|false|void)</string>
					<key>name</key>
					<string>keyword.parser</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>bkscr.parser.decnum</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\d+[\.\d*]([e|E][\+\-]?\d+)?)</string>
					<key>name</key>
					<string>keyword.number</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>bkscr.parser.hexnum</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(0x\d+([p|P][+|-]?\d+)?)</string>
					<key>name</key>
					<string>keyword.number</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>bkscr.parser.rawstring.begin</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>"</string>
                    <key>endCaptures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>bkscr.parser.rawstring.end</string>
                        </dict>
                    </dict>
                    <key>name</key>
                    <string>keyword.rawstring</string>
                    <key>patterns</key>
                    <string>([^"]*("")*)*</string>
                </dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>bkscr.parser.rawstring.begin</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>'</string>
                    <key>endCaptures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>bkscr.parser.rawstring.end</string>
                        </dict>
                    </dict>
                    <key>name</key>
                    <string>keyword.rawstring</string>
                    <key>patterns</key>
                    <string>([^']*(\\')*)*</string>
                </dict>
			</array>
		</dict>
	</dict>
	<key>uuid</key>
	<string>6BC8DE6F-2333-4C7E-AC3C-971385945346</string>
</dict>
</plist>
